name: SST Build
on: pull_request

permissions: write-all

# Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency:
  group: merge-${{ github.ref }}

jobs:
  BuildApp:
    runs-on: ubuntu-latest
    env:
      SMTP_CONFIG: ${{ secrets.SMTP_CONFIG }}
      SST_PRINT_LOGS: 1
      SST_STAGE: PR-${{ github.event.number }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v6
      - uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::912982098059:role/GitHubDeploy
          role-duration-seconds: 3600
          aws-region: us-east-2
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Install Playwright Browsers
        working-directory: ./packages/frontend
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: ./packages/frontend
        run: npm run test
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: playwright-report
          path: ./packages/frontend/playwright-report/
          retention-days: 7
      - name: Set Secret
        run: ./node_modules/.bin/sst secret set SMTP_CONFIG ${{ secrets.SMTP_CONFIG }}
      - name: Deploy app
        run: npm run deploy
      - name: Add Deploy URL Comment
        id: deploy-url
        uses: actions/github-script@v9
        with:
          result-encoding: string
          script: |
            const fs = require('fs')
            const body = fs.readFileSync('./.sst/outputs.json', 'utf-8');
            const parsedJson = JSON.parse(body);
            console.log(parsedJson);
            const siteUrl = parsedJson.site;
            const apiUrl = parsedJson.api;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Build Successful!\n\nPreview URL: ${siteUrl}\n\nAPI URL: ${apiUrl}`
            })
            return siteUrl;
      # - name: Check API Health
      #   run: |
      #     API_ENDPOINT=$(cat .sst/outputs.json | jq -r '.api')
      #     curl --fail-with-body $API_ENDPOINT/ping
      #     curl --fail-with-body $API_ENDPOINT/health
      - name: Run Pa11y CI
        run:  
          npx pa11y-ci --sitemap ${{steps.deploy-url.outputs.result}}/sitemap-index.xml --sitemap-find https://danklco.com  --sitemap-replace ${{steps.deploy-url.outputs.result}} --config .pa11yci
      - name: Page Speed Insights
        uses: jakepartusch/psi-action@v1.3
        with:
          url: ${{steps.deploy-url.outputs.result}}
          threshold: 60
          strategy: mobile
          key: ${{ secrets.PSI_API_KEY }}
